# Generated by Django 5.1.1 on 2024-09-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='classification',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
