# Generated by Django 5.1.1 on 2024-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageupload', '0002_image_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
